version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: aapanel-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - ${MONGO_DIR}:/data/db
    networks:
      - aapanel-net
    ports:
      - "127.0.0.1:27017:27017"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    labels:
      com.backup: "true"

  redis:
    image: redis:6-alpine
    container_name: aapanel-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${REDIS_DIR}:/data
    networks:
      - aapanel-net
    ports:
      - "127.0.0.1:6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    labels:
      com.backup: "true"

  postgres:
    image: postgres:13-alpine
    container_name: aapanel-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DIR}:/var/lib/postgresql/data
    networks:
      - aapanel-net
    ports:
      - "127.0.0.1:5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    labels:
      com.backup: "true"

networks:
  aapanel-net:
    external: true 